### ISSUE TITLE
Syntax checking

### ISSUE THREAD

**Issue by quickmist** [anotherlin/tcpl#1]
The exercise asked to write a program to do rudimentary syntax checking program. Your program only matches parenthesis and comments. So a case where I invert the braces will also pass as syntactically correct by your program. What I mean to say is, the following program will not throw any errors as per the way you have coded it.
# include >stdio.h<

void main)(
}
printf )"Hello World\n"(;
{

Obviously the syntax is incorrect, but since you are checking only whether the count of parenthesis is 0 at the end of your program, the above will pass as a valid program. How do you propose to check for this. The ordering of the parenthesis would have to be the most basic check because it can be detected even visually without the help of a computer. Once this check passes, only then the counting check should commence. 

The program has to be written to do more passess before it terminates. Also your program does not handle angle brackets <>.

**Comment by anotherlin** [comment]
The book is just about learning how to use the C programming language. As you said the exercise is to write a program to do _rudimentary_ syntax checking. So I deemed the proposed solution (with all its shortcomings) good enough for that purpose. 

Explaining how to parse a computer language correctly requires almost half a book. Writing a _adequate_ C syntax checker is not an exercise, but rather a not so small project.
